### PR TITLE
Cleanup + mostly all different paper types

### LINKED ISSUE #3: DK 11208 labels (38mm x 90mm).
Hi,

Could you please help me add support for DK 11208 labels (38mm x 90mm).

I expect that it follows closely to the PAPER_QL700 format, but I'm not quite sure what all the hex values correspond to in order for me to add this compatibility.

Best wishes,

James

### PR DESCRIPTION
**Pull request by soundstorm**
Did a cleanup on the indentation and added all the different paper types (Closes #3).
Option to increase print quality instead of print speed (default now switched; compile time option).

### CODE REVIEW

**Comment by Juul** [comment]
Wow amazing! I'll try to test this tonight. The timing of this and the fact that your profile says "never sleeping" makes me think that you might be using this for Covid-19 related sample tracking?

**Comment by soundstorm** [comment]
In Germany it was still regular daytime, but worked quite longer than I wanted. Just needed a better print quality for barcodes, which escalated a bit.
I also tested different drivers like 500, 570, 700, ... to check if there are other print options and bit-changes, but couldn't find any. Still wondering about the bits in the F1 titled param. For me it always reported 0x8E or with higher print quality 0xCE, while your code says 0x0E for 29x90mm and 0xA6 for endless paper.
But no, no Covid tracking :)

**Comment by Juul** [comment]
I just tested on a QL-700 with 29x90 paper and that works and yes greatly increased print quality!
I need to go dig up some endless paper but do you know if this fixes the issue where the minimum length you can print on the endless paper is 90 mm?

**Comment by Juul** [comment]
Oh, and for some reason I had a different copy of this repo [elsewhere](https://github.com/renegadebio/ql-printer-driver) but the only real changes were to the readme file. One change though was adding the license which per original author was GPLv3. Are you ok to license your additions as such?

**Comment by soundstorm** [comment]
No problem regarding the license :)

I tested quiet different lengths with my socket solution - these are the outputs, I haven't tested longer prints in last time, but I think I was successful more than once. Will check that again.
Here are my results :)

H1 | H2 | B1 | B2 | D1 | L (mm) | L (px, 300dpi) | L (mm)  | B2 << 8 \| B1 | LQ | L-LQ
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CC | 0A | 11001100 | 00001010 | 204 | 240 | 2834,64566929134 | 11110000 | 0000101011000010 | 2754 | 80,64566929134
56 | 0A | 01010110 | 00001010 | 86 | 230 | 2716,53543307087 | 11100110 | 0000101001001100 | 2636 | 80,53543307087
E0 | 09 | 11100000 | 00001001 | 224 | 220 | 2598,42519685039 | 11011100 | 0000100111010111 | 2519 | 79,42519685039
76 | 09 | 01110110 | 00001001 | 118 | 210 | 2480,31496062992 | 11010010 | 0000100101101101 | 2413 | 67,31496062992
F4 | 08 | 11110100 | 00001000 | 244 | 200 | 2362,20472440945 | 11001000 | 0000100011101100 | 2284 | 78,20472440945
8E | 08 | 10001110 | 00001000 | 142 | 190 | 2244,09448818898 | 10111110 | 0000100010000110 | 2182 | 62,09448818898
08 | 08 | 00001000 | 00001000 | 08 | 180 | 2125,9842519685 | 10110100 | 0000100000000000 | 2048 | 77,9842519685
92 | 07 | 10010010 | 00000111 | 146 | 170 | 2007,87401574803 | 10101010 | 0000011110001011 | 1931 | 76,87401574803
1C | 07 | 00011100 | 00000111 | 28 | 160 | 1889,76377952756 | 10100000 | 0000011100010101 | 1813 | 76,76377952756
A5 | 06 | 10100101 | 00000110 | 165 | 150 | 1771,65354330709 | 10010110 | 0000011010011111 | 1695 | 76,65354330709
2F | 06 | 00101111 | 00000110 | 47 | 140 | 1653,54330708661 | 10001100 | 0000011000101001 | 1577 | 76,54330708661
B9 | 05 | 10111001 | 00000101 | 185 | 130 | 1535,43307086614 | 10000010 | 0000010110110100 | 1460 | 75,43307086614
43 | 05 | 01000011 | 00000101 | 67 | 120 | 1417,32283464567 | 1111000 | 0000010100111110 | 1342 | 75,32283464567
CD | 04 | 11001101 | 00000100 | 205 | 110 | 1299,2125984252 | 1101110 | 0000010011001001 | 1225 | 74,2125984252
6D | 04 | 01101101 | 00000100 | 109 | 100 | 1181,10236220472 | 1100100 | 0000010001101001 | 1129 | 52,10236220472
E1 | 03 | 11100001 | 00000011 | 225 | 90 | 1062,99212598425 | 1011010 | 0000001111011110 | 990 | 72,99212598425
6B | 03 | 01101011 | 00000011 | 107 | 80 | 944,88188976378 | 1010000 | 0000001101101000 | 872 | 72,88188976378
F5 | 02 | 11110101 | 00000010 | 245 | 70 | 826,771653543307 | 1000110 | 0000001011110011 | 755 | 71,771653543307
7E | 02 | 01111110 | 00000010 | 126 | 60 | 708,661417322835 | 111100 | 0000001001111100 | 636 | 72,661417322835
08 | 02 | 00001000 | 00000010 | 08 | 50 | 590,551181102362 | 110010 | 0000001000000110 | 518 | 72,551181102362
92 | 01 | 10010010 | 00000001 | 146 | 40 | 472,44094488189 | 101000 | 0000000110010001 | 401 | 71,44094488189
27 | 01 | 00100111 | 00000001 | 39 | 30 | 354,330708661417 | 11110 | 0000000100100110 | 294 | 60,330708661417
A6 | 00 | 10100110 | 00000000 | 166 | 20 | 236,220472440945 | 10100 | 0000000010100110 | 166 | 70,220472440945
53 | 00 | 01010011 | 00000000 | 83 | 13 | 153,543307086614 | 1101 | 0000000001010011 | 83 | 70,543307086614

**Comment by Juul** [comment]
Thanks! I tested the 62 mm endless paper with very short prints and it works! (hard to get the printed label out of the printer though)

Two questions:

* Do you know how to change/disable the margins at the beginning and end of the print?
* Do you have a list of labels you've actually tested printing on?

**Comment by soundstorm** [comment]
Margin is even in the original P-touch tool set to minimum 3mm or which margins?

I still have 23x90 and 62x100 here, just printing on 62mm endless I'll check what happens if you print larger images than the mediatype is able to show, so maybe a restriction of print size is necessary.

**Pull request merged**
